#!/bin/sh
#
# Run the app against the local Supabase stack instead of the hosted project.
#
#   scripts/dev-local.sh              next dev, pointed at localhost
#   scripts/dev-local.sh -- --port 4000   extra args go to next dev
#
# No second credentials file, deliberately. The local stack's keys are
# regenerated by the CLI and would go stale in a checked-in file; this reads
# them from `supabase status` at launch, so they are always the live ones and
# there is one fewer place for a key to sit on disk.
#
# Next gives precedence to real environment variables over .env.local, so
# exporting them here is enough to redirect the whole app -- .env.local is never
# read for these four and never modified.

set -eu

REPO="$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd)"
cd "$REPO"

if ! command -v supabase >/dev/null 2>&1; then
  echo "FAILED: the Supabase CLI is not installed. brew install supabase/tap/supabase" >&2
  exit 1
fi

# OrbStack's socket is not at the default path until its GUI setup has run, so
# fall back to it when DOCKER_HOST is unset. Harmless if Docker Desktop is used.
if [ -z "${DOCKER_HOST:-}" ] && [ -S "$HOME/.orbstack/run/docker.sock" ]; then
  DOCKER_HOST="unix://$HOME/.orbstack/run/docker.sock"
  export DOCKER_HOST
fi

if ! status="$(supabase status -o env 2>/dev/null)"; then
  echo "FAILED: the local stack is not running. Start it with:" >&2
  echo "  supabase start" >&2
  exit 1
fi
eval "$status"

# The CLI has emitted both namings over time: legacy ANON_KEY/SERVICE_ROLE_KEY
# and the newer PUBLISHABLE_KEY/SECRET_KEY. Accept either -- supabase-js takes
# either kind of value in the same position, so only the name differs.
PUB="${PUBLISHABLE_KEY:-${ANON_KEY:-}}"
SEC="${SECRET_KEY:-${SERVICE_ROLE_KEY:-}}"
URL="${API_URL:-}"

if [ -z "$URL" ] || [ -z "$PUB" ] || [ -z "$SEC" ]; then
  echo "FAILED: could not read the local stack's URL and keys from 'supabase status -o env'." >&2
  exit 1
fi

export SUPABASE_URL="$URL"
export NEXT_PUBLIC_SUPABASE_URL="$URL"
export NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY="$PUB"
export SUPABASE_SECRET_KEY="$SEC"

echo "Local Supabase: $URL  (keys taken live from supabase status)"
echo
exec npm run dev -- "$@"
