-- More than one book on the shelf.
--
-- The pages table was built for this from the start: every row already carries
-- diary_id, every query already filters on it, and storage keys are already
-- prefixed diary<N>/. What was missing is the thing diary_id points AT -- until
-- now it was a number with no meaning, defaulting to 1 because there was only
-- ever one book.
--
-- Safe to re-run.

create table if not exists diaries (
  id         smallint    generated by default as identity primary key,
  -- The URL. Separate from the title so a book can be renamed without breaking
  -- every link to it.
  slug       text        not null unique,
  title      text        not null,
  subtitle   text,
  -- Shelf order, independent of id, so volumes can be arranged as they should
  -- be read rather than as they happened to be added.
  position   smallint    not null default 1,
  created_at timestamptz not null default now(),

  constraint diaries_slug_shape check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$')
);

-- The diary that already exists. Named here rather than left as "1".
insert into diaries (id, slug, title, position)
values (1, 'first-notebook', 'First Notebook', 1)
on conflict (id) do nothing;

-- The identity sequence knows nothing about a row inserted with an explicit id,
-- so without this the next diary added by the app would collide on id 1.
select setval(
  pg_get_serial_sequence('public.diaries', 'id'),
  coalesce((select max(id) from public.diaries), 1)
);

-- Now that a diary is a real thing, a page must belong to one that exists.
-- RESTRICT rather than CASCADE: deleting a book should not silently take its
-- pages -- and their storage objects, which SQL cannot clean up -- with it.
do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'pages_diary_id_fkey'
  ) then
    alter table public.pages
      add constraint pages_diary_id_fkey
      foreign key (diary_id) references public.diaries (id)
      on delete restrict;
  end if;
end $$;

-- Same posture as pages and profiles: closed to anon and authenticated, read
-- through the server with the service-role key. A shelf of book titles is less
-- sensitive than their contents, but it is still a list of what this person
-- keeps diaries about.
alter table diaries enable row level security;
